server:
  port: 8081
  servlet:
    context-path: /api/client
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 4KB
spring:
  application:
    name: lab-client-api